import type { NextPage } from "next";
import Head from "next/head";
import Main from "../containers/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Images</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </div>
  );
};

export default Home;
